apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: q776nbgnw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-68e4d85550.tl39.p3.openshiftapps.com/rhtap/rhtap-qe:bf197d5c15b1891425c4ef5bcbaaef40fb83b297@sha256:320f7fbc909207d22c109be0e35f7b86509cd2f8878b9a5b225ba5f913878255
          name: container-image
